<?php
/*
 * Logout (logout)
 * Digicel Panamá
 * @copyright Copyright (c) Móviles de Panamá, S.A. (http://www.movilesdepanama.com)
 *
 */

// Session Parameters
$loginKey = 'dGVzdF9yb21zMTQ4ODQ4Mjc5NTkyMw==';
$url = 'http://64.116.185.75:8001/dts-ws/DirectTopupSystemService?wsdl';

/* Transaction parameters
 *
 * loginKey (arg0)      = Generated by login.php, a new Login key must be generated every 24 hours
 * clientDate (arg1)    = Current date & time
 *
 */
$params = array(
    'arg0' => $loginKey
);

// Establish connection to WSDL
$client = new SoapClient($url, array("connection_timeout" => 15));

// Call logout method and store results in response array
$responseObject = $client->logout($params);
$responseArray = json_decode(json_encode($responseObject), TRUE);

// Display Results
print_r($responseArray);
