<?php
/*
 * Recharge MSISDN (rechargeMSISDN)
 * Digicel Panamá
 * @copyright Copyright (c) Móviles de Panamá, S.A. (http://www.movilesdepanama.com)
 *
 */

// Session Parameters
$loginKey = 'dGVzdF9yb21zMTQ4ODQ4Mjc5NTkyMw==';
$url = 'http://64.116.185.75:8001/dts-ws/DirectTopupSystemService?wsdl';

/* Transaction parameters
 *
 * loginKey (arg0)          = Generated by login.php, a new Login key must be generated every 24 hours
 * transactionID (arg1)     = Unique transaction ID for every recharge
 * clientDate (arg2)        = Current date & time
 * MSISDN (arg3)            = Destination phone number, always use the 507 prefix (507XXXXXXXX)
 * transactionAmount (arg4) = Recharge amount (double)
 * currency (arg5)          = Recharge currency, always use 'PAB'
 * cstomerName              = Optional ('' or null)
 *
 */
$params = array(
    'arg0'          => $loginKey,
    'arg1'          => '0000000013',
    'arg2'          => date('Y-m-d') . 'T' . date('H:i:s'),
    'arg3'          => '507' . '60751789',
    'arg4'          => '1.00',
    'arg5'          => 'PAB',
    'arg6'          => ''
);

// Establish connection to WSDL
$client = new SoapClient($url, array("connection_timeout" => 15));

// Call rechargeMSISDN method and store results in response array
$responseObject = $client->rechargeMSISDN($params);
$responseArray = json_decode(json_encode($responseObject), TRUE);

// Display Results
print_r($responseArray);
